# Generated by Django 4.0 on 2022-11-17 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('preguntas', '0002_preguntasrespondidas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='preguntasrespondidas',
            table='preguntasrespondidas',
        ),
        migrations.CreateModel(
            name='QuizUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Puntaje Total')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'quizusuario',
            },
        ),
        migrations.AddField(
            model_name='preguntasrespondidas',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preguntas.quizusuario'),
        ),
    ]
