# Generated by Django 4.0 on 2023-02-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0005_pregunta_max_puntaje_alter_elegirrespuesta_pregunta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizusuario',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Puntaje Total'),
        ),
    ]
